name: Bug report
description: Report a bug that you found, e.g. something is not working as expected
# title: ""
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping us to improve the driver!

        In the case you have difficulties to write in english, try the [deepl.com](https://www.deepl.com) translator.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Paste also screenshots, if needed.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Please describe in clear steps how to reproduce the issue. Paste also screenshots, if needed.
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. Paste also screenshots, if needed.
    validations:
      required: true

  - type: input
    id: driver_version
    attributes:
      label: Driver version
      description: Visible in the [driver log files](https://louisvdw.github.io/dbus-serialbattery/troubleshoot/#driver-log-files) or in the remote console/GUI under `SerialBattery` -> `Device` -> `Firmware version`
    validations:
      required: true

  - type: dropdown
    id: venus_os_device_type
    attributes:
      label: Venus OS device type
      description: Select your Venus OS device type.
      multiple: false
      # https://github.com/victronenergy/venus/wiki/machines
      options:
        - Please select
        - CCGX
        - Cerbo GX
        - Ekrano GX
        - GX Card (integrated in Victron device)
        - Octo GX
        - Raspberry Pi
        - VANcu GX
        - Venus_GX
    validations:
      required: true

  - type: input
    id: venus_os_version
    attributes:
      label: Venus OS version
      description: Visible in the remote console/GUI under `Settings` -> `Firmware` -> `Firmware version`
      placeholder: e.g. v2.94
    validations:
      required: true

  - type: dropdown
    id: bms_type
    attributes:
      label: BMS type
      description: Select your used BMS type.
      multiple: true
      # https://louisvdw.github.io/dbus-serialbattery/general/supported-bms
      options:
        - ANT BMS
        - Daly Smart BMS
        - ECS GreenMeter
        - HLPdataBMS4S
        - JKBMS / Heltec BMS
        - Life/Tian Power
        - MNB spi BMS
        - Renogy BMS
        - Revov
        - Seplos
        - Sinowealth
        - Smart BMS (LLT, JBD, Overkill Solar)
    validations:
      required: true

  - type: input
    id: cell_count
    attributes:
      label: Cell count
      description: Specify how many cells your battery has.
    validations:
      required: true

  - type: dropdown
    id: connection_type
    attributes:
      label: Connection type
      description: Select how you connected your battery to the Venus OS device.
      multiple: false
      options:
        - Please select
        - Serial USB adapter to TTL
        - Serial USB adapter to RS485
        - Raspberry Pi RS485 HAT
        - Bluetooth
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config file
      description: Paste your config file here. See [here](https://louisvdw.github.io/dbus-serialbattery/general/install#settings-locationpath) where you can find it. to get This will be automatically formatted into code, so no need for backticks.
      render: ini
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output here. See [here](https://louisvdw.github.io/dbus-serialbattery/troubleshoot/#driver-log-files) how to get the driver log files. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
