blank_issues_enabled: false

contact_links:
  - name: Troubleshoot
    about: Take a look how to troubleshoot.
    url: https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/

  - name: FAQ (Frequently Asked Questions)
    about: Take a look on the FAQ's.
    url: https://mr-manuel.github.io/venus-os_dbus-serialbattery_docs/faq/
