name: Feature request
description: Suggest an idea for this project
# title: ""
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping us to improve the driver!

        In the case you have difficulties to write in english, try the [deepl.com](https://www.deepl.com) translator.

        ## 🚨 IMPORTANT 🚨

        * Please try the `nightly` build from the `dev` first, if you are not already using it. Maybe the feature was already developed. See [here](https://louisvdw.github.io/dbus-serialbattery/general/install#nightly-build) how to install it.

  - type: textarea
    id: idea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder:

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder:

  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder:
