# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    # Run on changes in the master branch
    branches:
      - master
      - docusaurus

    # Run on changes in the docs folder
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Hosted GitHub runners have 7 GB of memory available, let's use 6 GB
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # execute only in Louisvdw repository
    if: github.repository_owner == 'Louisvdw'

    #defaults:
    #  run:
    #    working-directory: 'docs' # Here the path to the folder where package-lock.json is located.

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: yarn
          cache-dependency-path: './docs/yarn.lock' # THIS PATTERN did the trick for me.

      - name: Install dependencies
        run: yarn install --cwd ./docs --frozen-lockfile --non-interactive

      - name: Build
        run: yarn --cwd ./docs build

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
